config/routes.rb
NkuProject::Application.routes.draw do
  get "users/index"
  
  resources :users
  resources :sessions
  resources :blogs do
    resources :blog_comments
  end
  resources :blog_comments
  resources :cars do
    resources :comments
  end
  
  delete "sign_out", to: "sessions#destroy"
  get 'signin' => 'sessions#new'
  get 'signup' => 'users#new'
  get 'profile' => "users#profile"
  get 'all_users' => "users#all"
  
  root to: "users#index"
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :cars
  has_many :blogs
  mount_uploader :avatar, AvatarUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id].present?
  end
  helper_method :current_user
  
  before_action :require_login
  
  skip_before_action :require_login, only: [:new, :create]
  
  def logged_in?
    current_user != nil
  end
  
  private
  def require_login
    unless logged_in?
      redirect_to signin_path
    end
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def new
    @car = Car.new
  end
  
  def create
    @car = current_user.cars.create!(car_params)
    redirect_to profile_path, notice: 'Car has been created'
  end
  
  def show
    @car = Car.find(params[:id])
    @comment = Comment.new
  end
  
  private
  ## grabs all of the required user information needed for signup
  def car_params
    params.require(:car).permit!
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  ## creates a session for the user that is signing in
  def create
    user = User.find_by(email: session_params[:email])
    if user
      session[:user_id] = user.id
      redirect_to users_path, notice: "Signed in!"
    else
      flash[:error] = "Invalid email or password"
      render :new
    end
  end
  
  ## destroys the users session upon logging out
  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Signed out!"
  end
  
  private
  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  ## displays all of currently signed up users in the Bueller System
  # might later include only users who are currently signed in.
  def index
    @user = User.all
  end
  
  ## creates a new user upon submitting the sign up form
  # redirects user to index
  def create
    @user = User.create!(user_params)
    session[:user_id] = @user_id
    redirect_to users_path, notice: 'Hi, #{@user.username}. Welcome to the Car Place.'
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  private
  ## grabs all of the required user information needed for signup
  def user_params
    params.require(:user).permit!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
    when :notice then "alert alert-success"
    when :error then "alert alert-danger"
    when :alert then "alert alert-info"
    end
  end
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravitar_url(user)
    if user.profileImgUrl.present?
      user.profileImgUrl
    else
      hash = Digest::MD5.hexdigest(user.email)
      profileImgUrl = "http://www.gravatar.com/avatar/#{hash}"
    end
  end
end

app/views/cars/_form.html.erb
<div class="row col-sm-6">
  <%= form_for @car, :html => {:multipart => true} do |f| %>
    <div class="form-group">
      <%= f.label :make %>
      <%= f.text_field :make, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :model, 'Model' %>
      <%= f.text_field :model, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :year %>
      <%= f.text_field :year, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :color, 'Color' %>
      <%= f.text_field :color, class: 'form-control' %>
    </div>
  
    <div class="form-group">
      <%= f.label :engine_disp, 'Engine Displacement' %>
      <%= f.text_field :engine_disp, class: 'form-control' %>
    </div>
  
    <div class="form-group">
      <%= f.label :horsepower, 'Horsepower' %>
      <%= f.text_field :horsepower, class: 'form-control' %>
    </div>
  
    <div class="form-group">
      <%= f.label :torque, 'Torque' %>
      <%= f.text_field :torque, class: 'form-control' %>
    </div>
    
    <div class="form-group">
      <%= f.label :transmission, 'Transmission Type' %>
      <br />
      <%= f.radio_button(:transmission, 'Automatic') %>  
      <%= f.label(:transmission, 'Automatic') %>
      &nbsp;
      <%= f.radio_button(:transmission, 'Manual') %>  
      <%= f.label(:transmission, 'Manual') %>
      &nbsp;
      <%= f.radio_button(:transmission, 'DSG') %>  
      <%= f.label(:transmission, 'DSG') %>
    </div>
  
    <div class="form-group">
      <%= f.label :drivetrain, 'Drivetrain Type' %>
      <br />
      <%= f.radio_button(:drivetrain, 'RWD') %>  
      <%= f.label(:drivetrain, 'RWD') %>
      &nbsp;
      <%= f.radio_button(:drivetrain, 'AWD') %>  
      <%= f.label(:drivetrain, 'AWD') %>
      &nbsp;
      <%= f.radio_button(:drivetrain, 'FWD') %>  
      <%= f.label(:drivetrain, 'FWD') %>
    </div>
  
    <div class="form-group">
      <%= f.label :car_image, 'Car Image' %>
      <%= f.file_field :car_image %>
    </div>

    <%= f.submit class: 'btn btn-primary' %>
    &nbsp;or
    <%= link_to 'Cancel', users_path %>
  <% end %>
</div>

app/views/cars/new.html.erb
<h1>New Car Entry</h1>
<br />
<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Car Place</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container-fluid">
      <div class="span10">
        <nav class="navbar navbar-default" role="navigation">
          <div class="container-fluid">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="#">Car Place</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav">
                <li><%= link_to "Home", controller: "users" %></li>
                <li><%= link_to "All Users", all_users_path %></li>
              </ul>
              <ul class="nav navbar-nav navbar-right">
                <% if current_user %>
                  <div class="navbar-text"><li>Hi, <%= current_user.username %>!</li></div>
                  <li>
                    <div class="btn-group navbar-btn">
                      <%= link_to "View your profile", profile_path, class: "btn btn-primary" %>
                      <%= link_to "Sign out", sign_out_path, class: "btn btn-default", method: "delete"%>
                    </div>
                  </li>
                <% else %>
                  <%= link_to "Sign In", new_session_path, class: "btn btn-primary navbar-btn" %>
                  <%= link_to "Sign Up", new_user_path, class: "btn btn-default navbar-btn" %>
                <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </div>    
  <div class="container-fluid">

  <%= yield %>
    
  </div>

</body>
</html>

app/views/users/_form.html.erb
<div class="row col-sm-6">
  <%= form_for @user, :html => {:multipart => true} do |f| %>
    <div class="form-group">
      <%= f.label :full_name, "Full Name" %>
      <%= f.text_field :full_name, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :username, 'Username' %>
      <%= f.text_field :username, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :email %>
      <%= f.text_field :email, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :password, 'Password' %>
      <%= f.password_field :password, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :password_confirmation, 'Password Confirmation' %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
    </div>
  
    <div class="form-group">
      <%= f.label :avatar, "Avatar Image" %>
      <%= f.file_field :avatar %>
    </div>

    <%= f.submit class: 'btn btn-primary' %>
    &nbsp;or
    <%= link_to 'Cancel', users_path %>
  <% end %>
</div>

app/views/users/index.html.erb
<h1>Welcome to Car Place</h1>
<h3>The one stop for sharing your cars with everyone on the internet</h3>
<h4>And for people to make fun of the car you drive... Because, well, this is the internet.</h4>

<br />

<h2>Newest User</h2>
<table class="table">
    <tr>
      <th></th>
      <th>Username</th>
      <th>Full Name</th>
      <th>Email</th>
    </tr>
    <tr>
      <td><img style="height:9%;" src="<%= User.last.avatar.url %>" /></td>
      <td><%= User.last.username %></td>
      <td><%= User.last.full_name %></td>
      <td><%= User.last.email %></td>
    </tr>
</table>
<hr />

app/views/users/new.html.erb
<h1>New User Sign Up</h1>
<br />
<%= render 'form' %>

app/views/users/profile.html.erb
<h1><%= current_user.username %></h1>
<h6>(<%= current_user.full_name %>)</h6>
<div><img style="width:12%;" src="<%= current_user.avatar.url %>" /></div>
<h2><%= current_user.full_name %>'s Cars</h2>
<table class="table">
  <tr>
    <th>Make</th>
    <th>Model</th>
    <th>Year</th>
    <th>Color</th>
    <th>Image</th>
    <th>View</th>
  </tr>
  <% current_user.cars.each do |car| %>
    <tr>
      <td><%= car.make %></td>
      <td><%= car.model %></td>
      <td><%= car.year %></td>
      <td><%= car.color %></td>
      <td style="width:25%;"><img style="width:50%;" src="<%= car.car_image.url %>" /></td>
      <td><%= link_to "View", car_path(car), class: "btn btn-default" %></td>
    </tr>
  <% end %>
</table>

<h2><%= current_user.full_name %>'s Blog Entries</h2>
<hr />
<% current_user.blogs.each do |blog| %>
<h3><%= blog.title %></h3>
<small><p><b>Published On:</b> <%= blog.created_at %></p></small>
<p><%= blog.text %></p>
<%= link_to "View", blog_path(blog), class: "btn btn-primary" %>
<% end %>

<br />
<br />
<%= link_to "New Car?", new_car_path, class: "btn btn-default" %>
<%= link_to "New Blog Entry?", new_blog_path, class: "btn btn-default" %>
 